version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - PERSISTENCE=/tmp/localstack/state
    networks:
      - mynetwork

  myproject:
    build: .
    container_name: myproject
    depends_on:
      - localstack
    environment:
      - NASA_API_KEY=${NASA_API_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - LOCALSTACK_HOST=localstack
      - LOCALSTACK_S3_PORT=4566
    ports:
      - "8001:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
